version: '3.8'

services:
  web:
    build: .
    container_name: Angadi_flask_app
    ports:
      - '4535:5000' # Map external port 4535 to internal container port 5000
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgresql://myuser:mypassword@db/mydatabase # PostgreSQL URI
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: angadi_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pos_system_data:/var/lib/postgresql/data

volumes:
  pos_system_data:
